---
# tasks file for php

- name: Gather facts
  ansible.builtin.setup:
  register: system_facts
  tags:
    - always

- name: Get PHP version from OS repository
  ansible.builtin.shell:
    cmd: |
      set -o pipefail #
      false | apt-cache show php*fpm | egrep "Source: php[0-9\.]{3,6}" | head -n1 | awk '{print $2}' | sed 's/php//g'
  register: php_os_repo_version
  changed_when: false
  failed_when: false
  when: system_facts is defined and php.install_from_os_repo | bool
  tags:
    - php
    - php_version
    - os_repository

- name: Install PHP packages from OS repository - php version {{ php_os_repo_version.stdout }}
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  when: system_facts is defined and php.install_from_os_repo | bool
  loop:
    - php{{ php_os_repo_version.stdout }}
    - php{{ php_os_repo_version.stdout }}-cli
    - php{{ php_os_repo_version.stdout }}-fpm
    - php{{ php_os_repo_version.stdout }}-common
    - php{{ php_os_repo_version.stdout }}-curl
    - php{{ php_os_repo_version.stdout }}-mbstring
    - php{{ php_os_repo_version.stdout }}-xml
    - php{{ php_os_repo_version.stdout }}-zip
    - php{{ php_os_repo_version.stdout }}-mysql
    - php{{ php_os_repo_version.stdout }}-bcmath
    - php{{ php_os_repo_version.stdout }}-gd
    - php{{ php_os_repo_version.stdout }}-intl
    - php{{ php_os_repo_version.stdout }}-opcache
    - php{{ php_os_repo_version.stdout }}-redis
    - php{{ php_os_repo_version.stdout }}-memcached
    - php{{ php_os_repo_version.stdout }}-imagick
    - php{{ php_os_repo_version.stdout }}-xmlrpc
    - php{{ php_os_repo_version.stdout }}-xdebug
    - php{{ php_os_repo_version.stdout }}-pdo
    - php{{ php_os_repo_version.stdout }}-tidy
    - php{{ php_os_repo_version.stdout }}-yaml
    - composer
  notify:
    - Enable PHP-FPM service
    - Start PHP-FPM service
  tags:
    - php
    - os_repository
